imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

liip_functional_test:
    cache_sqlite_db: true

doctrine:
    dbal:
        host:     "%database.host%"
        port:     "%database.port%"
        dbname:   "%database.name%"
        user:     "%database.user%"
        password: "%database.password%"