security:
    encoders:
        Symfony\Component\Security\Core\User\User: sha512
        ADW\UserBundle\Entity\AdminUser: sha512
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

        admin_user_provider:
            id: adw.user.admin_user_repository

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        admin:
            provider: admin_user_provider
            pattern: ^/admin
            form_login:
                login_path: /admin/auth
                check_path: /admin/security/login/
                username_parameter: _email
                password_parameter: _password
                default_target_path: /admin
                success_handler: adw.user.security.admin_authentication_handler
                failure_handler: adw.user.security.admin_authentication_handler
                require_previous_session: false
            logout:
                path: /admin/logout
                target: /admin
                invalidate_session: false
            anonymous: true

        main:
           pattern: ^/
           form-login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
           logout: true
           anonymous: true

    access_control:
        - { path: ^/admin/auth$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: [ROLE_ADMIN, IS_AUTHENTICATED_REMEMBERED ]}

