security:
    encoders:
        Symfony\Component\Security\Core\User\User: sha512
        AppBundle\Entity\AdminUser: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        admin_user_provider:
            id: app.admin_user_repository

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        admin:
            provider: admin_user_provider
            pattern: ^/admin
            form_login:
#                login_path: /admin/auth
                check_path: /admin/security/login/
                username_parameter: _email
                password_parameter: _password
                default_target_path: /admin
                success_handler: admin.security.admin_authentication_handler
                failure_handler: admin.security.admin_authentication_handler
                require_previous_session: false
            logout:
                path: /admin/logout
            anonymous:    true
            remember_me:
                remember_me_parameter: '_remember_me'
                secret: '%secret%'
                lifetime: 86400
                path:     /admin/
                domain:   ~

        main:
            pattern: /
            anonymous: ~

    access_control:
        - { path: ^/admin/, role: ROLE_ADMIN }