services:
    app.admin.article:
        class: AppBundle\Admin\ArticleAdmin
        arguments: [~, AppBundle\Entity\Article, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, audit: false, group: Article, label: Article }