security:
    encoders:
        ADW\UserBundle\Entity\AdminUser: sha512

    role_hierarchy:
        ADW_ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ADW_ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        admin_user_provider:
            id: adw.user.admin_user_repository

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        admin:
            provider: admin_user_provider
            pattern: ^/adw-admin
            form_login:
                login_path: /adw-admin/auth
                check_path: /adw-admin/security/login/
                username_parameter: _email
                password_parameter: _password
                default_target_path: /admin
                success_handler: admin.security.admin_authentication_handler
                failure_handler: admin.security.admin_authentication_handler
                require_previous_session: false
            logout:
                path: /adw-admin/logout
                target: /adw-admin
                invalidate_session: false
            anonymous: true

        main:
            pattern: /
            anonymous: ~

    access_control:
        - { path: ^/adw-admin/auth$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/adw-admin/, role: [ROLE_ADMIN, IS_AUTHENTICATED_REMEMBERED ]}
